const TIME_SECOND = 1000;
const TIME_MINUTE = TIME_SECOND * 60;
const TIME_HOUR = TIME_MINUTE * 60;
const TIME_DAY = TIME_HOUR * 24;

export const TIME = {
  SECOND: TIME_SECOND,
  MINUTE: TIME_MINUTE,
  HOUR: TIME_HOUR,
  DAY: TIME_DAY,
};
